// Copies/minifies front-end libraries from node_modules into vendor/.
// CDNs are not reachable from the build container, so the site ships its own copies.
import { build } from 'esbuild';
import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const out = join(root, 'vendor');
const nm = join(root, 'node_modules');

// three.js addons to ship (paths relative to three/examples/jsm). 'three' stays external
// and resolves through the import map in index.html.
const THREE_ADDONS = [];

const COPIES = [
  ['gsap/dist/gsap.min.js', 'gsap.min.js'],
  ['gsap/dist/ScrollTrigger.min.js', 'ScrollTrigger.min.js'],
  ['gsap/dist/SplitText.min.js', 'SplitText.min.js'],
  ['lenis/dist/lenis.min.js', 'lenis.min.js'],
  ['lenis/dist/lenis.css', 'lenis.css'],
];

await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });

await build({
  entryPoints: [join(nm, 'three/build/three.module.js')],
  outfile: join(out, 'three.module.min.js'),
  bundle: true,
  format: 'esm',
  minify: true,
  legalComments: 'none',
  banner: { js: '/* three.js r186 — MIT License — https://threejs.org */' },
  logLevel: 'warning',
});

for (const addon of THREE_ADDONS) {
  await build({
    entryPoints: [join(nm, 'three/examples/jsm', addon)],
    outfile: join(out, 'three-addons', addon),
    bundle: true,
    format: 'esm',
    minify: true,
    external: ['three'],
    logLevel: 'warning',
  });
}

for (const [from, to] of COPIES) {
  const dest = join(out, to);
  await mkdir(dirname(dest), { recursive: true });
  await copyFile(join(nm, from), dest);
}

// Self-hosted variable fonts (no Google Fonts request → faster, GDPR-friendly).
// Only the latin + latin-ext subsets are shipped: enough for Polish and English.
const FONTS = ['syne', 'manrope'];
const SUBSETS = ['latin-ext', 'latin'];
let fontCss = '/* Generated by scripts/vendor.mjs from @fontsource-variable (SIL Open Font License) */\n';
await mkdir(join(out, 'fonts'), { recursive: true });
for (const font of FONTS) {
  const pkg = join(nm, '@fontsource-variable', font);
  const css = await readFile(join(pkg, 'index.css'), 'utf8');
  for (const subset of SUBSETS) {
    const file = `${font}-${subset}-wght-normal.woff2`;
    const block = css.match(new RegExp(`/\\* ${font}-${subset}-wght-normal \\*/\\s*@font-face \\{[^}]+\\}`));
    if (!block) throw new Error(`Missing @font-face for ${file}`);
    fontCss += `${block[0].replace(`./files/${file}`, `fonts/${file}`)}\n`;
    await copyFile(join(pkg, 'files', file), join(out, 'fonts', file));
  }
}
await writeFile(join(out, 'fonts.css'), fontCss);

console.log('vendor/ ready');
